CREATE SEQUENCE IF NOT EXISTS blacklist_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS users_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE blacklist
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id        INTEGER NOT NULL,
    blacklisted_at TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW(),
    reason         VARCHAR(100),
    token          TEXT,
    CONSTRAINT blacklist_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status     VARCHAR(10),
    role       VARCHAR(20),
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    password   VARCHAR(50),
    username   VARCHAR(50),
    email      VARCHAR(100),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE blacklist
    ADD CONSTRAINT fk8rrfcw4ypm4eayqtfu53tkl9r FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;